[package]
name = "rust-game"
version = "0.1.0"
authors = ["Jesse Stolwijk <stolwijkjesse@gmail.com>"]
edition = "2018"

[dependencies]
pancurses = "0.16"
rand = "0.4.2"
strum = "0.15.0"
strum_macros = "0.15.0"